export const affirmations = [
    "I am at peace with myself",
    "My faith is stronger than my fears",
    "I am healed from past hurts",
    "I do not allow other people's actions to ruin my day",
    "I forgive myself for my past mistakes",
    "I do not stress over things I cannot control",
    "I make time to take care of my body",
    "I wake up everyday choosing peace",
    "I am grateful for where I am in my life right now",
    "I forgive everyone who has hurt me for my own peace of mind",
    "I no longer take things personally",
    "I am at peace with my past",
    "I have the knowledge to make smart decisions for myself",
    "There are no blocks I cannot overcome",
    "My actions are intentional and they bring me closer to my goals",
    "I trust my intuition and I always make wise decisions",
    "Feeling confident, assured, and strong is a normal part of my everyday life",
    "My gifts are one-of-a-kind and unique to me",
    "I am doing my best",
    "I believe in myself",
    "Today is going to be a great day!",
    "I am grateful for all that I have",
    "I am proud of myself",
    "You're allowed to change your plans",
    "You don't have to be happy all the time",
    "Showing emotions is healthy and okay",
    "Authenticity is better than perfection",
    "You're amazing just the way you are",
    "Setbacks don't equal failure",
    "You are allowed to set boundaries",
    "You are more than an illness",
    "It's okay to rest",
    "Not everything you think is true",
    "Let yourself rest",
    "Don't compare yourself",
    "Speak kindly to yourself",
    "Let go of past mistakes",
    "You got this",
    "You'll figure it out",
    "You're a smart cookie",
    "I believe in you",
    "Mistakes don't make you less capable",
    "We are all works in progress",
    "You are capable",
    "You know more than you think",
    "If everything was easy you'd be bored",
    "I admire you for taking this on",
    "You're resourceful and clever",
    "You'll find a way",
    "I know you'll sort it out",
    "Struggling means you're learning",
    "You're doing a great job",
    "You make a difference in the world by simply existing in it",
    "You are worthy and deserving of respect",
    "You're an inspiration",
    "Your life is already a miracle of chance waiting for you to shape its destiny",
    "Your life is about to be incredible",
    "Failure is just another way to learn how to do something right",
    "I give myself permission to do what is right for me",
    "You can do it",
    "It is not a sprint, it is a marathon. One step at a time",
    "Success is the progressive realization of a worthy goal",
    "People with goals succeed because they know where they’re going",
    "All you need is the plan, the roadmap, and the courage to press on to your destination",
    "The opposite of courage in our society is not cowardice... it is conformity",
    "Whenever we’re afraid, it’s because we don’t know enough. If we understood enough, we would never be afraid",
    "The past does not equal the future",
    "The path to success is to take massive, determined action",
    "It’s what you practice in private that you will be rewarded for in public",
    "Small progress is still progress",
    "Don't worry if you find flaws in your past creations, it's because you've evolved",
    "Starting is the most difficult step - but you can do it",
    "Don't forget to enjoy the journey",
    "It's not a mistake, it's a learning opportunity",
]